[AzActLogAlertChangeNetworkSecGrp]
section = "5.2.3"
title = "Ensure that Activity Log Alert exists for Create or Update Network Security Group"
level = "L1"
version = "2.0"

[AzActLogAlertChangeSQLServerFWRule]
section = "5.2.7"
title = "Ensure that Activity Log Alert exists for Create or Update SQL Server Firewall Rule"
level = "L1"
version = "2.0"

[AzActLogAlertCreateOrUpdatePublicIPAddressRule]
section = "5.2.9"
title = "Ensure that Activity Log Alert exists for Create or Update Public IP Address rule"
level = "L1"
version = "2.0"

[AzActLogAlertCreateOrUpdateSecuritySolution]
section = "5.2.5"
title = "Ensure that Activity Log Alert exists for Create or Update Security Solution"
level = "L1"
version = "2.0"

[AzActLogAlertCreatePolicyAssignment]
section = "5.2.1"
title = "Ensure that Activity Log Alert exists for Create Policy Assignment"
level = "L1"
version = "2.0"

[AzActLogAlertDeleteNetworkSecGrp]
section = "5.2.4"
title = "Ensure that Activity Log Alert exists for Delete Network Security Group"
level = "L1"
version = "2.0"

[AzActLogAlertDeletePolicyAssignment]
section = "5.2.2"
title = "Ensure that Activity Log Alert exists for Delete Policy Assignment"
level = "L1"
version = "2.0"

[AzActLogAlertDeletePublicIPAddressRule]
section = "5.2.10"
title = "Ensure that Activity Log Alert exists for Delete Public IP Address rule"
level = "L1"
version = "2.0"

[AzActLogAlertDeleteSecuritySolution]
section = "5.2.6"
title = "Ensure that Activity Log Alert exists for Delete Security Solution"
level = "L1"
version = "2.0"

[AzActLogAlertDeleteSQLFirewallRule]
section = "5.2.8"
title = "Ensure that Activity Log Alert exists for Delete SQL Server Firewall Rule"
level = "L1"
version = "2.0"

[AzActNSGRDPLimitiation]
section = "6.1"
title = "Ensure that RDP access from the Internet is evaluated and restricted"
level = "L1"
version = "2.0"

[AzActNSGSSHLimitiation]
section = "6.2"
title = "Ensure that SSH access from the Internet is evaluated and restricted"
level = "L1"
version = "2.0"

[AzAppRegistration]
section = "1.14"
title = "Ensure That <i>Users Can Register Applications</i> Is Set to <i>No</i>"
level = "L1"
version = "2.0"

[AzASCDefaultPolicy]
section = "2.1.14"
title = "Ensure Any of the ASC Default Policy Settings are Not Set to <i>Disabled</i>"
level = "L1"
version = "2.0"

[AzAutoprovisioning]
section = "2.1.15"
title = "Ensure that Auto provisioning of <i>Log Analytics agent for Azure VMs</i> is Set to <i>On</i>"
level = "L1"
version = "2.0"

[AzGuestInvite]
section = "1.16"
title = "Ensure that <i>Guest invite restrictions</i> is set to <i>Only users assigned to specific admin roles can invite guest users</i>"
level = "L2"
version = "2.0"

[AzGuestRestrictions]
section = "1.15"
title = "Ensure That <i>Guest users access restrictions</i> is set to <i>Guest user access is restricted to properties and memberships of their own directory objects</i>"
level = "L1"
version = "2.0"

[AzKeyVKeyExpirationNonRBAC]
section = "8.2"
title = "Ensure that the Expiration Date is set for all Keys in Non RBAC Key Vaults"
level = "L1"
version = "2.0"

[AzKeyVKeyExpirationRBAC]
section = "8.1"
title = "Ensure that the Expiration Date is set for all Keys in RBAC Key Vaults"
level = "L1"
version = "2.0"

[AzKeyVLogging]
section = "5.1.5"
title = "Ensure that logging for Azure Key Vault is <i>Enabled</i>"
level = "L1"
version = "2.0"

[AzKeyVSecretExpirationNonRBAC]
section = "8.4"
title = "Ensure that the Expiration Date is set for all Secrets in Non RBAC Key Vaults"
level = "L1"
version = "2.0"

[AzKeyVSecretExpirationRBAC]
section = "8.3"
title = "Ensure that the Expiration Date is set for all Secrets in RBAC Key Vaults"
level = "L1"
version = "2.0"

[AzKeyVSoftDelete]
section = "8.5"
title = "Ensure the Key Vault is Recoverable"
level = "L1"
version = "2.0"

[AzPSQLLogCheckpoints]
section = "4.3.2"
title = "Ensure Server Parameter <i>log_checkpoints</i> is set to <i>ON</i> for PostgreSQL Database Server"
level = "L1"
version = "2.0"

[AzPSQLLogConnections]
section = "4.3.3"
title = "Ensure server parameter <i>log_connections</i> is set to <i>ON</i> for PostgreSQL Database Server"
level = "L1"
version = "2.0"

[AzPSQLLogConnectionThrottling]
section = "4.3.5"
title = "Ensure server parameter <i>connection_throttling</i> is set to <i>ON</i> for PostgreSQL Database Server"
level = "L1"
version = "2.0"

[AzPSQLLogDisconnections]
section = "4.3.4"
title = "Ensure server parameter <i>log_disconnections</i> is set to <i>ON</i> for PostgreSQL Database Server"
level = "L1"
version = "2.0"

[AzRestrictUserAccessGroupFeature]
section = "1.18"
title = "Ensure that <i>Restrict user ability to access groups features in the Access Pane</i> is Set to <i>Yes</i>"
level = "L2"
version = "2.0"

[AzSQLAuditingEnabled]
section = "4.1.1"
title = "Ensure that <i>Auditing</i> is set to <i>On</i>"
level = "L1"
version = "2.0"

[AzSQLAuditingRetention]
section = "4.1.6"
title = "Ensure that <i>Auditing</i> Retention is <i>greater than 90 days</i>"
level = "L1"
version = "2.0"

[AzSQLServerAzADAdmin]
section = "4.1.4"
title = "Ensure that Azure Active Directory Admin is Configured for SQL Servers"
level = "L1"
version = "2.0"

[AzSQLServerInboundTraffic]
section = "4.1.2"
title = "Ensure no Azure SQL Databases allow ingress from 0.0.0.0/0 (ANY IP)"
level = "L1"
version = "2.0"

[AzStorAcAllowTrustedServices]
section = "3.9"
title = "Ensure <i>Allow Azure services on the trusted services list to access this storage account</i> is Enabled for Storage Account Access"
level = "L2"
version = "2.0"

[AzStorAcContainerPublicAccess]
section = "3.7"
title = "Ensure that <i>Public access level</i> is disabled for storage accounts with blob containers"
level = "L1"
version = "2.0"

[AzStorAcCustomKeys]
section = "3.12"
title = "Ensure Storage for Critical Data are Encrypted with Customer Managed Keys"
level = "L2"
version = "2.0"

[AzStorAcInfraEncrypt]
section = "3.2"
title = "Ensure that <i>Enable Infrastructure Encryption</i> for Each Storage Account in Azure Storage is Set to <i>enabled</i>"
level = "L2"
version = "2.0"

[AzStorAcKeyLastRotation]
section = "3.4"
title = "Ensure that Storage Account Access Keys are Periodically Regenerated"
level = "L1"
version = "2.0"

[AzStorAcKeyRotationReminder]
section = "3.3"
title = "Ensure that <i>Enable key rotation reminders</i> is enabled for each Storage Account"
level = "L1"
version = "2.0"

[AzStorAcMinTLSVersion]
section = "3.15"
title = "Ensure the <i>Minimum TLS version</i> for storage accounts is set to <i>Version 1.2</i>"
level = "L1"
version = "2.0"

[AzStorAcNetworkAccess]
section = "3.8"
title = "Ensure Default Network Access Rule for Storage Accounts is Set to Deny"
level = "L1"
version = "2.0"

[AzStorAcSecureTransfer]
section = "3.1"
title = "Ensure that <i>Secure transfer required</i> is set to <i>Enabled</i>"
level = "L1"
version = "2.0"

[AzStorAcSoftDelete]
section = "3.11"
title = "Ensure Soft Delete is Enabled for Azure Containers and Blob Storage"
level = "L1"
version = "2.0"

[AzSubscriptionPolicy]
section = "1.25"
title = "Ensure That <i>Subscription Entering AAD Directory</i> and <i>Subscription Leaving AAD Directory</i> Is Set To <i>Permit No One</i>"
level = "L2"
version = "2.0"

[AzVirtMManagedDiskUsage]
section = "7.2"
title = "Ensure Virtual Machines are utilizing Managed Disks"
level = "L1"
version = "2.0"

[DfCEAdditionalMailAlert]
section = "2.1.19"
title = "Ensure <i>Additional email addresses</i> is Configured with a Security Contact Email"
level = "L1"
version = "2.0"

[DfCEAdditionalMailAlertSeverity]
section = "2.1.20"
title = "Ensure That <i>Notify about alerts with the following severity</i> is Set to <i>High</i>"
level = "L1"
version = "2.0"

[DfCEMailSecAlerts]
section = "2.1.18"
title = "Ensure That <i>All users with the following roles</i> is set to <i>Owner</i>"
level = "L1"
version = "2.0"

[GroupAllowsSelfService]
section = "1.20"
title = "Ensure that <i>Owners can manage group membership requests in the Access Panel</i> is set to <i>No</i>"
level = "L2"
version = "2.0"

[GroupAllowUserToCreateSecGroups]
section = "1.19"
title = "Ensure that <i>Users can create security groups in Azure portals, API or PowerShell</i> is set to <i>No</i>"
level = "L2"
version = "2.0"

[GroupM365GroupManagement]
section = "1.21"
title = "Ensure that <i>Users can create Microsoft 365 groups in Azure portals, API or PowerShell</i> is set to <i>No</i>"
level = "L2"
version = "2.0"

[UserAllAdminsHaveMFA]
section = "1.1.2"
title = "Ensure that <i>Multi-Factor Auth Status</i> is <i>Enabled</i> for all Privileged Users"
level = "L1"
version = "2.0"

[UserAllowCreationOfAzureTenants]
section = "1.3"
title = "Ensure that <i>Users can create Azure AD Tenants</i> is set to <i>No</i>"
level = "L1"
version = "2.0"

[UserAllUserHaveMFA]
section = "1.1.3"
title = "Ensure that <i>Multi-Factor Auth Status</i> is <i>Enabled</i> for all Non-Privileged Users"
level = "L2"
version = "2.0"

[UserCanAddGalleryApps]
section = "1.13"
title = "Ensure that <i>Users can add gallery apps to My Apps</i> is set to <i>No</i>"
level = "L1"
version = "2.0"

[UserConsent]
section = "1.11"
title = "Ensure <i>User consent for applications</i> is set to <i>Do not allow user consent</i>"
level = "L1"
version = "2.0"

[UserNotifyAdminOnPasswordReset]
section = "1.10"
title = "Ensure That <i>Notify all admins when other admins reset their password?</i> is set to <i>Yes</i>"
level = "L2"
version = "2.0"

[UserNotifyUserOnPasswordReset]
section = "1.9"
title = "Ensure that <i>Notify users on password resets?</i> is set to <i>Yes</i>"
level = "L1"
version = "2.0"

[UserPasswordBadPasswordList]
section = "1.7"
title = "Ensure that a Custom Bad Password List is set to <i>Enforce</i> for your Organization"
level = "L1"
version = "2.0"

[UserPasswordResetRequires2Methods]
section = "1.6"
title = "Ensure That <i>Number of methods required to reset</i> is set to <i>2</i>"
level = "L1"
version = "2.0"

[UserReconfirmAuthenticationInformation]
section = "1.8"
title = "Ensure that <i>Number of days before users are asked to reconfirm their authentication information</i> is not set to <i>0</i>"
level = "L1"
version = "2.0"

[UserRequireMFADevJoin]
section = "1.22"
title = "Ensure that <i>Require Multi-Factor Authentication to register or join devices with Azure AD</i> is set to <i>Yes</i>"
level = "L1"
version = "2.0"

[UserRestrictAccessToAdminPortal]
section = "1.17"
title = "Ensure That <i>Restrict access to Azure AD administration portal</i> is Set to <i>Yes</i>"
level = "L1"
version = "2.0"

[AzSecurityDefaultsO365]
section = "1.1.1"
title = "Ensure Security Defaults is enabled on Azure Active Directory"
level = "L1"
version = "2.0"